<?php 
$KEY_USER = "XXXXXXXXX"; 
$KEY_PASSWORD = "testpassword_XXXXXXXXXXXXXXXXXXXXXX";  
$KEY_JS = "62114337:testkey_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"; 
$KEY_SHA256 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXX";
$URL_BASE = "https://api.micuentaweb.pe/api-payment/V4/Charge/CreatePayment"; //ESTA URL PUEDE VARIAR SEGUN EL API QUE USEN